---
- name: Render Helm value file
  set_fact:
    helm_value_content: "{{ lookup('template', 'templates/' + item + '.yaml.j2') }}"
  with_items:
    - 'value'

- name: Create pgadmin4 Helm value file
  copy:
    content: '{{ helm_value_content }}'
    dest: '{{ helm_value_files_path }}/pgadmin4-values.yaml'
    mode: '666'

- name: Install Helm pgadmin4
  command: 'helm install pgadmin4 -f {{ helm_value_files_path }}/pgadmin4-values.yaml --version 1.3.2 runix/pgadmin4'
  register: result

- name: Helm install result information
  debug:
    msg:
      - '{{result.stdout}}'
