---
- name: Render Helm value file
  set_fact:
    helm_value_content: "{{ lookup('template', 'templates/' + item + '.yaml.j2') }}"
  with_items:
    - 'value'

- name: Create Postgresql Helm value file
  copy:
    content: '{{ helm_value_content }}'
    dest: '{{ helm_value_files_path }}/postgresql-values.yaml'
    mode: '666'

- name: Install Helm Postgresql
  command: 'helm install postgresql -f {{ helm_value_files_path }}/postgresql-values.yaml --version 9.7.1 bitnami/postgresql'
  register: result

- name: Helm install result information
  debug:
    msg:
      - '{{result.stdout}}'
