---
- name: Render Helm value file
  set_fact:
    helm_value_content: "{{ lookup('template', 'templates/' + item + '.yaml.j2') }}"
  with_items:
    - 'value'

- name: Create mongoadmin Helm value file
  copy:
    content: '{{ helm_value_content }}'
    dest: '{{ helm_value_files_path }}/mongoadmin-values.yaml'
    mode: '666'

- name: Install Helm mongoadmin
  command: 'helm install mongoadmin -f {{ helm_value_files_path }}/mongoadmin-values.yaml --version 1.3.0 cowboysysop/mongo-express'
  register: result

- name: Helm install result information
  debug:
    msg:
      - '{{result.stdout}}'
